name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup pnpm
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2

      - name: Install Dependencies
        run: pnpm install

      - name: Publish
        uses: wtrocki/npm-publish-monorepo-action@2.0.0
        with:
          workspace: ./packages # Required
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
